apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart: https://127.0.0.1:6443/static/charts/cilium-1.15.5.tgz
  bootstrap: true
  valuesContent: |-
    k8sServiceHost: "127.0.0.1"
    k8sServicePort: 6443
    kubeConfigPath: /etc/rancher/k3s/k3s.yaml
    kubeProxyReplacement: strict
    autoDirectNodeRoutes: false
    ipv4NativeRoutingCIDR: ""
    bpf:
      hostLegacyRouting: false
      masquerade: true
    tunnelProtocol: geneve
    routingMode: "tunnel"
    tunnelPort: 6081
    disableIptablesFeederRules: true
    l7Proxy: false
    loadBalancer:
      mode: dsr
      dsrDispatch: geneve
    image:
      repository: "%{SYSTEM_DEFAULT_REGISTRY}%rancher/cilium"
      useDigest: false
    operator:
      replicas: 1
      image:
        repository: "%{SYSTEM_DEFAULT_REGISTRY}%rancher/operator"
        useDigest: false
